/*  Deletetable.sql -- created to delete all the table, view, procedures at a time that was created for the game databases */


-- drop table
DROP TABLE IF EXISTS MEDALLIST;
DROP TABLE IF EXISTS TEAM;
DROP TABLE IF EXISTS ATHLETE ;
DROP TABLE IF EXISTS COACH;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS TOTAL_MEDAL ;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS SCHEDULE;

-- drop VIEW
DROP VIEW MEDALLIST_TEAM ;


-- DELETE PROCEDURE 
DROP PROCEDURE IF EXISTS CAL_TOTAL_MEDALS;
DROP PROCEDURE IF EXISTS Counting_Medal_By_discipline;
DROP PROCEDURE IF EXISTS cd;
